package view;

import java.util.ResourceBundle;
import javax.swing.JFrame;
import utils.PropertiesHelper;

public class AboutForm extends javax.swing.JFrame {

  /** Creates new form AboutForm */
  public AboutForm() {
    PropertiesHelper.initialize();
    ResourceBundle about = PropertiesHelper.getAbout();
    initComponents();
    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    //this.jTextArea1.setText(AboutController.Text);
    this.jLabel1.setText(about.getString("about.about"));
    this.jTextArea1.setText(about.getString("about.text"));
    //this.jLabel4.setText(AboutController.Version);
    this.jLabel3.setText(about.getString("about.version"));    
    this.jLabel4.setText(about.getString("about.versionNumber"));
    //this.jLabel5.setText(AboutController.Dev);
    this.jLabel2.setText(about.getString("about.notes"));
    this.jLabel5.setText(about.getString("about.developer"));
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTextArea1.setBackground(new java.awt.Color(201, 201, 201));
    jTextArea1.setColumns(20);
    jTextArea1.setEditable(false);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    jTextArea1.setEnabled(false);
    jTextArea1.setMinimumSize(new java.awt.Dimension(128, 24));
    jTextArea1.setPreferredSize(new java.awt.Dimension(128, 96));
    jTextArea1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
    jTextArea1.setSelectionColor(new java.awt.Color(1, 1, 1));
    jScrollPane1.setViewportView(jTextArea1);

    jLabel1.setText("About");

    jLabel2.setText("Version");

    jLabel3.setText("Notes");

    jLabel4.setText("jLabel4");

    jLabel5.setText("jLabel5");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
              .addComponent(jLabel3)
              .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
              .addComponent(jLabel2)
              .addGap(18, 18, 18)))
          .addComponent(jLabel1))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addContainerGap())
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addGap(219, 219, 219))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel5))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new AboutForm().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
